ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION

LABEL maintainer=$AUTHOR version=$VERSION

ARG TARGETOS
ARG TARGETARCH

COPY ./release/${TARGETOS}/${TARGETARCH}/nfs-provisioner /usr/local/bin/nfs-provisioner

ENTRYPOINT ["/usr/local/bin/nfs-provisioner"]
