ARG BASE=alpine:3

FROM $BASE

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=v4.0.2
ARG TARGETOS
ARG TARGETARCH
LABEL maintainer=${AUTHOR} version=${VERSION}

COPY ./release/${TARGETOS}/${TARGETARCH}/nfs-provisioner /usr/local/bin/nfs-provisioner

ENTRYPOINT ["/usr/local/bin/nfs-provisioner"]
